config/routes.rb
Rails.application.routes.draw do

  get 'rails/generate'
  get 'rails/migration'
  get 'rails/rename_fight_id_column_to_fights'
  get 'comments/create'
  get 'comments/destroy'

  post "likes/:post_id/create" => "likes#create"
  post "likes/:post_id/destroy" => "likes#destroy"

  post "fights/:goal_id/create" => "fights#create"
  post "fights/:goal_id/destroy" => "fights#destroy"
  
  get "login" => "users#login_form"
  post "login" => "users#login"
  post "logout" => "users#logout"
  post "users/:id/update" => "users#update"
  get "users/:id/edit" => "users#edit"
  post "users/create" => "users#create"
  get "signup" => "users#new"
  get "users/index" => "users#index"
  get "users/:id" => "users#show"

  get "users/:id/likes" => "users#likes"
  get "users/:id/goals" => "users#goals"
 
  get "posts/index" => "posts#index"
  get "posts/new" => "posts#new"
  get "posts/:id" => "posts#show"
  post "posts/create" => "posts#create"
  get "posts/:id/edit" => "posts#edit"
  post "posts/:id/update" => "posts#update"
  post "posts/:id/destroy" => "posts#destroy"

  get "goals/index" => "goals#index"
  get "goals/new" => "goals#new"
  get "goals/:id" => "goals#show"
  post "goals/create" => "goals#create"
  get "goals/:id/edit" => "goals#edit"
  post "goals/:id/update" => "goals#update"
  post "goals/:id/destroy" => "goals#destroy"

  resources :posts, except: [:index] do
    resources :comments, only: [:create, :destroy]
  end
  
  get "/" => "home#top"
  get "about" => "home#about"
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, {presence: true, length: {maximum: 230}}
  validates :user_id, {presence: true}
  validates :point, {presence: true}
  
  belongs_to :user

  def user
    return User.find_by(id: self.user_id)
  end

  has_many :comments, dependent: :destroy


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user
  before_action :ensure_correct_user, {only: [:edit, :update, :destroy]}

  def index
    @posts = Post.all.order(created_at: :desc).page(params[:page]).per(5)
    @users = User.all.order(id: :desc).page(params[:page]).per(5)
  end
  
  def show
    @post = Post.find_by(id: params[:id])
    @user = @post.user
    @likes_count = Like.where(post_id: @post.id).count
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(
      content: params[:content], 
      user_id: @current_user.id,
      point: params[:point]
    )
    @post.save

    if params[:post_picture]
      @post.post_picture = "#{@post.id}.jpg"
      image = params[:post_picture]
      File.binwrite("public/post_pictures/#{@post.post_picture}", image.read)
    end

    if @post.save
      flash[:notice] = "投稿完了！"
    redirect_to("/posts/index")
    else
      render("posts/new")
    end
  end

  

  def edit
    @post=Post.find_by(id: params[:id])
  end

  def update
    @post=Post.find_by(id: params[:id])
    @post.content = params[:content]
    @post.point = params[:point]
    if @post.save
      flash[:notice]="上書き完了！"
    redirect_to("/posts/index")
    else 
      flash[:notice]="上書き失敗"
      render("posts/edit")
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    flash[:notice] = "投稿を削除"
    redirect_to("/posts/index")
  end

  def ensure_correct_user
    @post = Post.find_by(id: params[:id])
    if @post.user_id != @current_user.id
      flash[:notice] = "不正アクセス"
      redirect_to("/posts/index")
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">編集する</h1>
    <div class="form">
    <div class="form-body">
    <% @post.errors.full_messages.each do |message| %>
      <div class="form-error">
        <%= message %>
      </div>
    <% end %>
  <%= form_tag("/posts/#{@post.id}/update") do %>
    <h1>《投稿内容》</h1>
    <textarea name="content"><%= @post.content %></textarea>
    <h1>※画像変更不可</h1>
    <h1>《主観的幸福度》</h1>
        <div class="happy-tag">
        <%= select_tag(:point , options_for_select(["1","2","3","4","5","6","7","8","9","10"])) %>
        </div>
    <input type="submit" value="保存">
  </div>
</div>
<% end %>
</div>
</div>

app/views/posts/index.html.erb
<div class="main posts-index">
  <div class="container1">
  <h1 class="form-heading">幸せ共有広場</h1>
  <div class="goal-setting">
  <li><%= link_to("幸せを共有する", "/posts/new") %></li>
  </div>
    <% @posts.each do |post| %>
      <div class="posts-index-item">
        <div class="post-left">
        
          <img src="<%= "/user_images/#{post.user.image_picture}" %>">
        </div>
        <div class="post-right">
         <div class="status">
          <p>《 <%= post.user.status %> 》</p>
         </div>
          <div class="post-user-name">
            <%= link_to(post.user.name, "/users/#{post.user.id}") %>
            <h1>幸福度【　<%= post.point %>　】</h1>
          </div>
          <div class="post-content">
          <%= link_to(post.content, "/posts/#{post.id}") %>
          </div>
          <div class="post-picture">
          <% if post.post_picture %>
           <img src="<%= "/post_pictures/#{post.post_picture}" %>">
          <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <div class="pagination">
    <%= paginate @posts %>
  </div>
</div>
</div>
 <div class="explain">
   <h2>幸せ共有広場とは？</h2>
   <p>どんなに些細で小さくてもいいから、今日１日の中で良い出来事・幸福と感じた出来事を共有してみよう！<br>気分が前向きになった出来事なら何でもOK！</p>
   <p>例：１日で２回も褒められた!, 新発売を大人買いした!</p>
</div>
<div class="side2">
<h2>　 ユーザー一覧 　</h2>
<% @users.each do |user| %>
  <div class="users-index-item2">
    <div class="user-left2">
      <img src="<%= "/user_images/#{user.image_picture}" %>">
    </div>
    <div class="user-right2">
      <%= link_to(user.name, "/users/#{user.id}") %>
    </div>
  </div>
<% end %>
<div class="pagination">
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">投稿する</h1>
   <%= form_tag("/posts/create", {multipart: true}) do %>
    <div class="form">
      <div class="form-body">
        <% @post.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>
        <h1>《投稿内容》</h1>
        <textarea name="content"><%= @post.content %></textarea>

        <h1>《画像》</h1>
        <input type = "file" name ="post_picture">

        <h1>《主観的幸福度　1＝" 普通 " , 10=" 言葉に出来ないほど嬉しい "》</h1>
        <div class="happy-tag">
        <%= select_tag(:point , options_for_select(["1","2","3","4","5","6","7","8","9","10"])) %>
        </div>
        <input type="submit" value="投稿">
      </div>
    </div>
  　<% end %>
  
  </div>
</div>

app/views/posts/show.html.erb
<div class="main posts-show">
  <div class="container-post">
    <div class="posts-show-item">
      <div class="post-user-name">
        <img src="<%= "/user_images/#{@user.image_picture}" %>">
        <%= link_to(@user.name, "/users/#{@user.id}") %>
        <h1>幸福度【　<%= @post.point %>　】</h1>
      </div>
      <p>
        <%= @post.content %>
      </p>
      <div class="post-picture">
      <% if @post.post_picture %>
      <img src="<%= "/post_pictures/#{@post.post_picture}" %>">
      <% end %>
      </div>
      <div class="post-time">
        <%= @post.created_at %>
      </div>
     
      <% if Like.find_by(user_id: @current_user.id, post_id: @post.id) %>
        <%= link_to("/likes/#{@post.id}/destroy", {method: "post"}) do %>
          <span class="fa fa-hand-holding-heart like-btn-unlike"></span>
     <% end %>
      <% else %>
        <%= link_to("/likes/#{@post.id}/create", {method: "post"}) do %>
          <span class="fa fa-hand-holding-heart like-btn"></span>   
        <% end %>
      <% end %>
      <%= @likes_count %>
      

      <% if @post.user_id == @current_user.id %>
      <div class="post-menus">
        <%= link_to("編集", "/posts/#{@post.id}/edit") %>
        <%= link_to("削除", "/posts/#{@post.id}/destroy", {method: "post"}) %>
      </div>
      <% end %>
    </div>

    <div class="comment-name">
    <h3>コメント一覧</h3
    </div>
    <%= form_for [@post, @comment] do |f| %>     
        <%= f.text_area :comment, class: "form-control"%>
        <%= f.submit '送信', class: "btn-sm btn-primary" %>
    <% end %>
   
  
    <table>
      <thead>
          <td class="nameee">《 投稿者 》</td>
          <td class="comment2">《 コメント内容 》</td>
      </thead>
      <tbody>
        <% @comments.each do |comment| %>
          <tr>
            <td class="nameee"><%= comment.user.name %></td>
            <td class="commenttt"><%= comment.comment %></td>
            <% if comment.user_id == @current_user.id %>
            <td><%= link_to "削除", post_comment_path(@post, comment), method: :delete %></td>
            <% end %>
            
          </tr>
        <% end %>
      </tbody>
    </table>

    
  </div>
</div>